name: Publish docs via GitHub Pages
on:
  push:
    tags:
      - v*
  # Allow the workflow to be triggered also manually.
  workflow_dispatch:

jobs:
  build:
    name: Deploy docs
    runs-on: ubuntu-latest
    steps:
      - name: Checkout mainline
        uses: actions/checkout@v2

      - name: Deploy docs
        uses: mhausenblas/mkdocs-deploy-gh-pages@161dbcc77f9adadd31b5a517e0c04a76e96bac6c
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
