name: Validate numpy docstrings

on:
  pull_request:
  push:
  schedule:
    # * is a special character in YAML so you have to quote this string
    - cron: '0 */72 * * *'

jobs:
  build:
    runs-on: ${{ matrix.os }}
    environment:
      name: test
    strategy:
      fail-fast: false
      matrix:
        python-version: ['3.10']
        os: [ubuntu-latest]

    steps:
      - name: Check out Git repository
        uses: actions/checkout@v5

      - name: set up python '3.10'
        uses: actions/setup-python@v5.6.0
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          export PDPIPE__LOAD_STAGE_ATTRIBUTES=False
          python -m pip install --upgrade pip
          python -m pip install --only-binary=all numpy
          python -m pip install numpydoc
          python -m pip install -e ".[test]"

      - name: Validate numpy docstrings
        run: |
          export PDPIPE__LOAD_STAGE_ATTRIBUTES=False
          export PDPIPE__LOAD_CORE_AS_MODULE=True
          python dev/scripts/numpydoc_validate.py
